from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.shared.models import MenuCategory, MenuItem


class MenuRepository(Protocol):
    async def list_categories(self) -> list[MenuCategory]: ...
    async def get_category(self, category_id: UUID) -> MenuCategory | None: ...
    async def save_category(self, category: MenuCategory) -> None: ...

    async def list_items(self) -> list[MenuItem]: ...
    async def get_item(self, item_id: UUID) -> MenuItem | None: ...
    async def save_item(self, item: MenuItem) -> None: ...
